version: "3"
services:
  udagram-reverse-proxy:
    image: heikoschmidt1187/udagram-reverse-proxy
    ports:
      - 80:80
    restart: always
    depends_on:
      - udagram-api-users
      - udagram-api-feed
      - udagram-frontend
  udagram-api-users:
    image: heikoschmidt1187/udagram-api-users
    ports:
      - 8081:8081
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8081"
  udagram-api-feed:
    image: heikoschmidt1187/udagram-api-feed
    ports:
      - 8080:8080
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8080"
  udagram-frontend:
    image: heikoschmidt1187/udagram-frontend
    ports:
      - 8100:8100

