apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-users
  name: udagram-api-users
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: udagram-api-users
