apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: udagram-reverse-proxy
