apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontent
  name: udagram-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external
    spec:
      containers:
      - image: heikoschmidt1187/udagram-frontend
        name: udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8100
      restartPolicy: Always
